name: Public SFTP Test Server (Alternative)
on:
  workflow_dispatch:

jobs:
  setup-sftp:
    runs-on: ubuntu-latest
    steps:
      - name: Setup SFTP Server with full permissions
        run: |
          # 使用更简单的配置
          docker run -d \
            --name sftp-server \
            -p 2222:22 \
            atmoz/sftp:alpine \
            testuser:testpass:::upload

      - name: Wait for container to start
        run: |
          sleep 15

      - name: Setup ngrok
        run: |
          curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null
          echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | sudo tee /etc/apt/sources.list.d/ngrok.list
          sudo apt update
          sudo apt install ngrok -y
          ngrok config add-authtoken ${{ secrets.NGROK_AUTH_TOKEN }}

      - name: Start ngrok tunnel
        run: |
          ngrok tcp 2222 > /tmp/ngrok.log &
          sleep 10
          
          TUNNEL_INFO=$(curl -s localhost:4040/api/tunnels)
          PUBLIC_URL=$(echo $TUNNEL_INFO | grep -o '"public_url":"[^"]*"' | head -1 | cut -d'"' -f4)
          
          echo "Public SFTP Server: $PUBLIC_URL"
          echo "Username: testuser"
          echo "Password: testpass"

      - name: Display detailed connection info
        run: |
          echo "=================================================="
          echo "SFTP Test Server - Full Access Test"
          echo "Username: testuser"
          echo "Password: testpass"
          if [ ! -z "$PUBLIC_URL" ]; then
            PORT=$(echo $PUBLIC_URL | cut -d':' -f3)
            HOST=$(echo $PUBLIC_URL | cut -d':' -f2 | sed 's/\/\///')
            echo ""
            echo "Test commands:"
            echo "1. sftp -P $PORT testuser@$HOST"
            echo "2. In SFTP session:"
            echo "   mkdir test_folder"
            echo "   put /path/to/local/file.txt"
            echo "   ls -la"
          fi
          echo "=================================================="

      - name: Keep alive
        run: sleep 1800