name: Public SFTP Server
on:
  workflow_dispatch:

jobs:
  setup-public-sftp:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup SFTP Server
        run: |
          docker run -d \
            --name sftp-server \
            -p 22:22 \
            atmoz/sftp \
            testuser:testpass:1001:::upload

      - name: Install and setup ngrok
        run: |
          wget https://bin.equinox.io/c/bNyj1m1r5gY/ngrok-v3-stable-linux-amd64.tgz
          tar -xzf ngrok-v3-stable-linux-amd64.tgz
          chmod +x ngrok

      - name: Start ngrok tunnel
        run: |
          ./ngrok tcp 22 > /tmp/ngrok.log &
          sleep 5
          NGROK_URL=$(curl -s localhost:4040/api/tunnels | grep -o "tcp://[0-9a-z.]*:[0-9]*")
          echo "Public SFTP endpoint: $NGROK_URL"
          echo "Username: testuser"
          echo "Password: testpass"

      - name: Keep server alive
        run: sleep 1800  # 保持30分钟