name: Public SFTP Test Server
on:
  workflow_dispatch:

jobs:
  setup-sftp:
    runs-on: ubuntu-latest
    steps:
      - name: Setup SFTP Server
        run: |
          docker run -d \
            --name sftp-server \
            -p 2222:22 \
            atmoz/sftp:alpine \
            testuser:testpass:1001

      - name: Wait for container to start
        run: |
          sleep 15
          docker ps

      - name: Setup ngrok with auth
        run: |
          # 安装ngrok
          curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null
          echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | sudo tee /etc/apt/sources.list.d/ngrok.list
          sudo apt update
          sudo apt install ngrok -y

      - name: Configure ngrok auth
        run: |
          ngrok config add-authtoken ${{ secrets.NGROK_AUTH_TOKEN }}

      - name: Start ngrok tunnel
        run: |
          # 启动ngrok
          ngrok tcp 2222 > /tmp/ngrok.log &
          sleep 10
          
          # 获取公网地址
          TUNNEL_INFO=$(curl -s localhost:4040/api/tunnels)
          PUBLIC_URL=$(echo $TUNNEL_INFO | grep -o '"public_url":"[^"]*"' | head -1 | cut -d'"' -f4)
          
          if [ ! -z "$PUBLIC_URL" ]; then
            echo "Public SFTP Server: $PUBLIC_URL"
            echo "Username: testuser"
            echo "Password: testpass"
            echo "Example connection: sftp -P ${PUBLIC_URL##*:} testuser@${PUBLIC_URL%:*}"
            echo "PUBLIC_SFTP_URL=$PUBLIC_URL" >> $GITHUB_ENV
          else
            echo "Failed to get public URL"
          fi

      - name: Display connection info
        run: |
          echo "=================================================="
          echo "SFTP Test Server Information:"
          echo "Username: testuser"
          echo "Password: testpass"
          echo "Local testing: sftp -P 2222 testuser@localhost"
          if [ ! -z "${{ env.PUBLIC_SFTP_URL }}" ]; then
            echo "Public URL: ${{ env.PUBLIC_SFTP_URL }}"
            echo "Public port: $(echo ${{ env.PUBLIC_SFTP_URL }} | cut -d':' -f3)"
          fi
          echo "Server will remain active for 10 minutes"
          echo "=================================================="

      - name: Keep alive
        run: sleep 600